#ITS100 Lecture1 Introduction to Computers and Python Lab1.5
print("h")
print("he")
print("hel")
print("hell")
print("hello")
print("hello ")
print("hello w")
print("hello wo")
print("hello wor")
print("hello worl")
print("hello world")