#ITS100 Lecture2 Variables, Input and Output Lab 2.9
a =input("Enter the first number: ")
print(" ")
b =input("Enter the second number: ")
print(" ")
c =input("Enter the third number: ")
print(" ")
d=input("Enter the first number: ")
print(" ")
e=input("Enter the second number: ")
print(" ")
f=input("Enter the third number: ")
print(" ")
a,b,c,d,e,f,= int(a),int(b),int(c),int(d),int(e),int(f)
print("Reverse order of %d %d %d %d %d %d --> %d %d %d %d %d %d"%(a,b,c,d,e,f,f,e,d,c,b,a))